### ISSUE TITLE
not enough notes available for automata unit 3.

### ISSUE THREAD

**Issue by devasheeshG** [shar-mayank/All-Notes-Sem-V#1]

**Comment by shar-mayank** [comment]
Hey, sorry for that. check the commit eac19a5 for that. @gauransh415 just uploaded a pdf of automata unit 3. It might help. Thanks.

**Comment by devasheeshG** [comment]
ab toh padh chuka mai, now take my dick.

**Comment by devasheeshG** [comment]
maafi
